project:
  name: crypto_forecast
  seed: 42
  run_name: chronos2_logret

paths:
  processed_dir: /gpfs/work5/0/prjs1859/Crypto_Forecast/data/processed
  checkpoints_dir: /gpfs/work5/0/prjs1859/Crypto_Forecast/outputs/checkpoints
  predictions_dir: /gpfs/work5/0/prjs1859/Crypto_Forecast/outputs/predictions

data:
  interval: "4h"  # supported: "1d" | "4h" | "1h" | "15m"
  symbol_col: symbol
  keep_feature_cols: # all become past_covariates except target_logreturn
    - open
    - high
    - low
    - close
    - volume

    # technical indicators
    - st_value
    - st_direction
    - reversal_upper
    - reversal_lower

    # target_col, so excluded from past_covariates
    - target_logreturn 

  min_history: 30

split:
  train_start: "2022-12-01 00:00:00"
  train_end: "2024-04-30 23:59:59"

  val_start: "2024-08-01 00:00:00"
  val_end: "2024-12-31 23:59:59"
  
  test_start: "2025-04-01 00:00:00"
  test_end: "2025-10-31 23:59:59"

model:
  model_id: amazon/chronos-2
  device_map: cuda
  torch_dtype: bfloat16
  init_mode: pretrained   # pretrained | random
  loss_mode: native       # native|weighted_extreme_time_decay|magnitude_weighted|directional_hybrid
  loss_params:
    loss_quantile_extreme_gamma: 2.0
    loss_quantile_extreme_power: 2.0
    loss_time_decay: 0.8
    loss_magnitude_alpha: 1.0
    loss_directional_lambda: 0.2
    loss_directional_temperature: 0.1
  context_length: 1024
  prediction_length: 3    # this is the "horizon" for train, i.e., how many steps into the future to predict
  quantile_levels: [0.1, 0.2, 0.8, 0.9]
  cross_learning: false

train:
  enabled: true
  batch_size: 128
  learning_rate: 1.0e-5
  num_steps: 1500
  finetune_mode: full
  finetuned_ckpt_name: finetuned-ckpt
  remove_printer_callback: true

wandb:
  enabled: true
  project: crypto_chronos2_multi-interval
  entity: 574817827-university-of-amsterdam
  tags: [chronos2, logreturn, fullshot]

infer:
  enabled: true
  model_source: local      # local | hf
  hf_model_id: amazon/chronos-2
  horizon: 1
  include_multi_horizon: false
  ckpt_subdir: null   # if null, use <checkpoints_dir>/<run_name>/finetuned-ckpt
  batch_size: 64
