project:
  name: crypto_forecast
  seed: 42
  run_name: chronos2_logret

paths:
  raw_dir: /gpfs/work5/0/prjs1859/market_info/cleaned
  processed_dir: /gpfs/work5/0/prjs1859/Crypto_Forecast/data/processed
  checkpoints_dir: /gpfs/work5/0/prjs1859/Crypto_Forecast/outputs/checkpoints
  predictions_dir: /gpfs/work5/0/prjs1859/Crypto_Forecast/outputs/predictions

# Data conversion + modeling scope
universe:
  file_pattern_template: "*_{interval}_Binance_cleaned.csv"
  symbols: []  # empty means use all matched files

data:
  interval: "1d"  # supported: "1d" | "4h" | "1h" | "15m"
  timestamp_col: starttime
  symbol_col: symbol
  target_price_col: close
  keep_feature_cols: # most of them are the past_covariates in chronos2
    - open
    - high
    - low
    - close
    - volume
    - quotevolume
    - activebuyvolume
    - activebuyquotevolume
    - tradenum
    - target_logreturn # this is target_col, so excluded from past_covariates
  min_history: 30
  freq: "1D"

split:
  train_start: "2023-12-01"
  train_end: "2025-08-31"
  val_end: "2025-11-30"
  # test is (val_end, +inf)

model:
  model_id: amazon/chronos-2
  device_map: cuda
  torch_dtype: bfloat16
  init_mode: pretrained   # pretrained | random
  loss_mode: native       # native|weighted_extreme_time_decay|magnitude_weighted|directional_hybrid
  loss_params:
    loss_quantile_extreme_gamma: 2.0
    loss_quantile_extreme_power: 2.0
    loss_time_decay: 0.8
    loss_magnitude_alpha: 1.0
    loss_directional_lambda: 0.2
    loss_directional_temperature: 0.1
  context_length: 1024
  prediction_length: 3    # this is the "horizon" for train, i.e., how many steps into the future to predict
  quantile_levels: [0.1, 0.2, 0.8, 0.9]
  cross_learning: false

train:
  enabled: true
  batch_size: 128
  learning_rate: 1.0e-5
  num_steps: 1500
  finetune_mode: full
  finetuned_ckpt_name: finetuned-ckpt
  remove_printer_callback: true

wandb:
  enabled: true
  project: crypto_forecast
  entity: 574817827-university-of-amsterdam
  tags: [chronos2, logreturn, fullshot]

infer:
  enabled: true
  model_source: local      # local | hf
  hf_model_id: amazon/chronos-2
  horizon: 1
  include_multi_horizon: false
  ckpt_subdir: null   # if null, use <checkpoints_dir>/<run_name>/finetuned-ckpt
  batch_size: 64
